#!/usr/bin/env ruby

#############################################################################
## Useful for manually testing things like the LocalSpace sending heartbeats.
##
#############################################################################

$: << "."
$: << "../lib"
$: << "../ext"

require 'thread'
require 'socket'
require 'marinda'
require 'marinda/verboseclient'

Thread.abort_on_exception = true

sock_path = "/tmp/localts-test.sock"
$c = Marinda::Client.new sock_path, :scope => :local
$g = Marinda::Client.new sock_path
$c = Marinda::VerboseClient.new $c, "c"
$g = Marinda::VerboseClient.new $g, "g"

$g.consume_stream [] do |tuple|
  p tuple
end
