#!/usr/bin/env ruby

#############################################################################
## Useful for manually testing things like the LocalSpace sending heartbeats.
##
#############################################################################

$: << "."
$: << "../lib"
$: << "../ext"

require 'thread'
require 'socket'
require 'marinda'
require 'marinda/verboseclient'

Thread.abort_on_exception = true

SOCKET = "/tmp/localts-test.sock"
s = UNIXSocket.open SOCKET
$c = Marinda::VerboseClient.new(Marinda::Client.new(s), "c")
$c.hello
$g = Marinda::VerboseClient.new $c.global_commons, "g"

i = 1
while gets()
  t = ["FOO", i]
  i += 1
  p t
  $g.write t
end

