#!/usr/bin/env ruby

#############################################################################
## Useful for manually testing things like the LocalSpace sending heartbeats.
##
## --------------------------------------------------------------------------
## Copyright (C) 2009 The Regents of the University of California.
## 
## This file is part of Marinda.
## 
## Marinda is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Marinda is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with Marinda.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

$: << "."
$: << "../lib"

require 'thread'
require 'socket'
require 'marinda'
require 'marinda/verboseclient'

Thread.abort_on_exception = true

SOCKET = "/tmp/localts-test.sock"
s = UNIXSocket.open SOCKET
$c = Marinda::VerboseClient.new(Marinda::Client.new(s), "c")
$c.hello
$g = Marinda::VerboseClient.new $c.global_commons, "g"

i = 1
while gets()
  t = ["FOO", i]
  i += 1
  p t
  $g.write t
end

