#!/usr/bin/env ruby

#############################################################################
## Useful for manually testing things like the LocalSpace sending heartbeats.
##
#############################################################################

$: << "."
$: << "../lib"
$: << "../ext"

require 'thread'
require 'socket'
require 'marinda'
require 'marinda/verboseclient'

Thread.abort_on_exception = true

sock_path = "/tmp/localts-test.sock"
$g = Marinda::Client.new sock_path
$g = Marinda::VerboseClient.new $g, "g"

i = 1
while gets()
  t = ["FOO", i]
  i += 1
  p t
  $g.write t
end

